### PR TITLE
Parameterize remote access configs

### PR DESCRIPTION
**Pull request by JDShu**

### CODE REVIEW

**Comment by JDShu** [comment]
@pranav @PaulFurtado

**Comment by PaulFurtado** [comment]
You should PR this into the upstream module, not ours

**Comment by bbeaudreault** [comment]
Why don't we merge here first, then we can PR from here to the upstream. That way we can get it now without waiting for them to merge

**Comment by pranav** [comment]
Upstream looks completely dead and we are many commits ahead anyway on `hsmaster`

**Pull request merged**
